# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 09:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170730_0028'),
        ('blog', '0002_auto_20170517_1929'),
    ]

    operations = [
    ]
